name: Run Python Script

on:
  workflow_dispatch:

env:
  assistant_id: ${{secrets.ASSISTANT_ID}}
  email_sender: ${{secrets.EMAIL_SENDER}}
  gmail_password: ${{secrets.GMAIL_PASSWORD}}
  openai_api_key: ${{secrets.OPENAI_API_KEY}}
  vector_store_id: ${{secrets.VECTOR_STORE_ID}}

  

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Run Python Script
      run: |
        pip install requests
        python legal.py
